name = "tacticbook"
version = "0.1.0"
defaultTargets = ["tacticbook"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "main"

[leanOptions]
#weak.verso.examples.suggest = true
linter.typography.quotes = false
linter.typography.dashes = false
weak.linter.verso.manual.headerTags = true

[[lean_lib]]
name = "Tacticbook"

[[lean_exe]]
name = "tacticbook"
root = "Main"
